### ISSUE TITLE
'panctl' hangs

### ISSUE THREAD

**Issue by Janed89** [matrix-org/pantalaimon#82] opened 2021-01-14 12:49 UTC
`panctl` (version 0.8.0) becomes completely unresponsive when I run the `list-servers` command. I have to kill it externally since even Ctrl + C doesn't have any effect.

`dbus-monitor` shows the request to the daemon but no reply

```
method call time=1610628200.263091 sender=:1.582 -> destination=org.pantalaimon1 serial=10 path=/org/pantalaimon1; interface=org.pantalaimon1.control; member=ListServers
```

The daemon itself works and proxies connections but despite setting `LogLevel = debug` only keeps repeating these messages
```
[2021-01-14 12:45:40.747789] INFO: pantalaimon: Trying to decrypt sync
[2021-01-14 12:45:40.748063] INFO: pantalaimon: Decrypting sync
```

**Comment by poljar** [comment] 2021-01-14 13:19
I think this is a duplicate of https://github.com/matrix-org/pantalaimon/issues/81. A new release will happen this week.

**Closed** 2021-01-20 07:42 UTC
