### ISSUE TITLE
Messages in e2ee rooms instantly fail to send

### ISSUE THREAD

**Issue by Sorunome** [matrix-org/pantalaimon#41] opened 2020-02-17 17:10 UTC
In some e2ee rooms messages instantly fail to send. Receiving messages still works fine, though. Pan dose not generate any log output.

**Comment by jaller94** [comment] 2020-02-29 14:20
Does your client have any output?

I have a problem that fits the description above with the following error message:
```
(Test Silvy's encryption) @silvy:matrix.org :: pong
Error sending event Error: This room is configured to use encryption, but your client does not support encryption.
    at _encryptEventIfNeeded (/home/jaller94/Git/silvy-matrix/node_modules/matrix-js-sdk/lib/client.js:2552:11)
    at /home/jaller94/Git/silvy-matrix/node_modules/matrix-js-sdk/lib/client.js:2439:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
setting pendingEvent status to not_sent in !OTarMzbwCaWRibWRMa:matrix.org
```

I use matrix-js-sdk 5.0.1.

**Comment by Sorunome** [comment] 2020-02-29 16:27
Soru discussed with @poljar the issue in the matrix room: The reply is `Max retries exceeded while trying to send the message`, meaning it is inside of nio, that it is receiving over and over that the client (pan) should upload new keys.

Conversation starting here https://matrix.to/#/!SFgClZZicGzvdPoxUG:matrix.org/$iVR71LEhL6k_jZNfv12lnxoyfQp7ur9RGahS7LkWqIg?via=matrix.org&via=sorunome.de&via=ggc-project.de

**Comment by poljar** [comment] 2020-02-29 16:53
@Sorunome you increased the retry limit, right? Did the issue occur again after you increased it? What value did you use?

**Comment by Sorunome** [comment] 2020-02-29 16:55
yes, soru increased it to 10 (it was 5 originally). There haven't been any issues with it since.

**Comment by Randshot** [comment] 2020-03-02 11:55
#38 seems to be related.

**Comment by poljar** [comment] 2020-03-02 11:57
Yes, those two are duplicates.

**Comment by ReK2Fernandez** [comment] 2020-04-09 20:24
> yes, soru increased it to 10 (it was 5 originally). There haven't been any issues with it since.
> 
> Just increasing the retry limit doesn't seem like a proper fix, though >.<

where did you increment this retry limit? do not see the option on the example config.

**Comment by poljar** [comment] 2020-04-09 20:28
It's edited in the source of matrix-nio, the latest release contains the increased retries.

**Comment by ReK2Fernandez** [comment] 2020-04-09 21:20
```
ur/pantalaimon 0.5.1-2 (+1 0.39%) (Installed)
    Pantalaimon is an end-to-end encryption aware Matrix reverse proxy daemon.
```
This is the version I have, should I uninstall and clone master from github?

**Comment by poljar** [comment] 2020-04-10 06:31
No, the fix is in matrix-nio, 0.10.

**Comment by ReK2Fernandez** [comment] 2020-04-12 02:46
@poljar ahh ok got it!

**Comment by poljar** [comment] 2020-04-17 13:27
Any chance of fishing out the HTTP logs? That is what is the HTTP server responding with when this fails.

**Comment by poljar** [comment] 2020-05-13 15:12
Same as for https://github.com/matrix-org/pantalaimon/issues/38#issuecomment-628056741 since this issue is a duplicate of that one.

**Closed by poljar** 2020-05-13 15:12 UTC
